//
//  PickerIcons.swift
//  DaySet
//
//  Created by Dalton Turner on 2/12/24.
//

enum IconPickerOptions: String, CaseIterable {
    case listBullet = "list.bullet"
    case bookmarkFill = "bookmark.fill"
    case mappin = "mappin"
    case giftFill = "gift.fill"
    case birthdayCakeFill = "birthday.cake.fill"
    case book = "book"
    case calendar = "calendar"
    case person = "person"
    case gear = "gear"
    case house = "house"
    case cart = "cart"
    case phone = "phone"
    case pencil = "pencil"
    case bell = "bell"
    case tag = "tag"
    case heart = "heart"
    case starFill = "star.fill"
    case airplane = "airplane"
    case car = "car"
    case bicycle = "bicycle"
    case leaf = "leaf"
    case moon = "moon"
    case sunMin = "sun.min"
    case alarm = "alarm"
    case map = "map"
    case musicNote = "music.note"
    case tv = "tv"
    case laptop = "laptopcomputer"
    case gamecontroller = "gamecontroller"
    case paintbrush = "paintbrush"
    case camera = "camera"
    case bag = "bag"
    case flask = "flask"
    case sportscourt = "sportscourt"
    case figureWalk = "figure.walk"
    case pawprint = "pawprint"
    case eyedropper = "eyedropper"
    case wrench = "wrench"
    case scissors = "scissors"
    case printer = "printer"
    case houseFill = "house.fill"
    case lock = "lock"
    case key = "key"
    case clock = "clock"
    case megaphone = "megaphone"
    case flame = "flame"
    case lightbulb = "lightbulb"
    case globe = "globe"
}

